server:
  port: 9296
  
spring:
  application:
    name: config-server
  bus:
    enabled: true
  cloud:
    config:
      server:
        git:
         uri: https://github.com/sulemanbashir/ecommerce-config-server
         username: {username}
         password: {password}
         clone-on-start: true